README.md
README.zh_CN.md

docs: add new acknowledgment

---

README.md
README.zh_CN.md

docs: add FAQ link

---

rush.json

chore: allow all type email

---

.github/CODEOWNERS

add backend owners into CODEOWNERS

chore: backend owners

---

backend/application/search/project_search.go
backend/application/search/resource_search.go

This merger is to address the issue https://github.com/coze-dev/coze-studio/issues/139 This submission fixes duplicate calls to. packIntelligenceData in the code and optimizes the code logic, reducing the use of go routine

fix: Optimize the GetDraftIntelligenceList function and reduce the use of goroutine

---

backend/application/workflow/workflow.go
frontend/packages/workflow/adapter/base/src/utils/get-enabled-node-types.ts
frontend/packages/workflow/playground/src/components/node-render/node-render-new/content/index.tsx
frontend/packages/workflow/playground/src/node-registries/index.ts
frontend/packages/workflow/playground/src/node-registries/json-stringify/components/inputs/index.tsx
frontend/packages/workflow/playground/src/node-registries/json-stringify/constants.ts
frontend/packages/workflow/playground/src/node-registries/json-stringify/data-transformer.ts
frontend/packages/workflow/playground/src/node-registries/json-stringify/form-meta.tsx
frontend/packages/workflow/playground/src/node-registries/json-stringify/form.tsx
frontend/packages/workflow/playground/src/node-registries/json-stringify/index.ts
frontend/packages/workflow/playground/src/node-registries/json-stringify/node-content.tsx
frontend/packages/workflow/playground/src/node-registries/json-stringify/node-registry.ts
frontend/packages/workflow/playground/src/node-registries/json-stringify/node-test.ts
frontend/packages/workflow/playground/src/node-registries/json-stringify/types.ts
frontend/packages/workflow/playground/src/nodes-v2/constants.ts

feat(workflow): add workflow json-stringify node
增加 Workflow 中 JSON 序列化节点
en: add workflow json stringify node 
zh(optional): 增加 Workflow 中 JSON 序列化节点

feat: add json-stringify node

---

backend/application/knowledge/init.go
backend/conf/model/template/model_template_openai.yaml
backend/go.mod
backend/go.sum
backend/infra/impl/document/ocr/veocr/ve_ocr.go
backend/infra/impl/embedding/ark/ark.go
backend/infra/impl/embedding/wrap/ollama.go
backend/infra/impl/modelmgr/static/modelmgr.go
docker/.env.example

feat
en:
- improve logs and errors for knowledge
- support ollama embedding model
zh(optional): 
- 优化知识库日志和报错内容
- 支持 ollama 部署的向量模型

feat: init improvements

---

docker/docker-compose.yml

fix
- [ √] This PR title match the format: \<type\>(optional scope): \<description\>
- [√ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ √] Add documentation if the current PR requires user awareness at the usage level.
en:
When ` docker compose --profile '*' up -d` start project, throw `You may need to escape any $ with another $` error.
zh(optional): 
Fixes #146

fix: escape '$' to '$$' in docker-compose.yml file

---

.github/CODEOWNERS
common/config/subspaces/default/pnpm-lock.yaml
frontend/packages/studio/open-platform/open-chat/package.json

feat: Chat supports Q&A nodes

---

.github/CODEOWNERS

chore: better owners config

---

backend/application/knowledge/init.go
backend/infra/impl/document/searchstore/vikingdb/vk_test.go
backend/infra/impl/embedding/ark/ark.go
backend/infra/impl/embedding/http/http.go
backend/infra/impl/embedding/http/http_test.go
backend/infra/impl/embedding/wrap/dense_only.go
backend/infra/impl/embedding/wrap/ollama.go
backend/infra/impl/embedding/wrap/openai.go
docker/.env.example

feat
en:
- support user configuration of EMBEDDING_MAX_BATCH_SIZE
zh(optional): 
- 支持用户配置 EMBEDDING_MAX_BATCH_SIZE
fixes https://github.com/coze-dev/coze-studio/issues/291

feat: support EMBEDDING_MAX_BATCH_SIZE

---

frontend/config/tailwind-config/src/tailwind-contents.ts

fix: fix infinite loop causing startup failure in Windows environment

---

backend/application/base/pluginutil/api.go
backend/domain/agent/singleagent/service/single_agent_impl.go
backend/domain/plugin/conf/load_plugin.go
backend/domain/plugin/internal/dal/agent_tool_draft.go
backend/domain/plugin/internal/dal/tool_draft.go
backend/domain/plugin/repository/tool_impl.go
backend/domain/plugin/service/exec_tool.go

…e effect
fix
en:
zh(optional):

fix(plugin): setting the default value of the agent tool does not take effect

---

backend/api/model/crossdomain/plugin/openai.go
backend/domain/plugin/internal/openapi/convert_protocol.go

feat(plugin): remove schema retriction for plugin server url

---

frontend/packages/agent-ide/bot-plugin/export/src/component/file-import/plugin-info-confirm/utils.ts
frontend/packages/studio/plugin-form-adapter/src/components/plugin-form-content/utils.tsx

fix: remove https validation from plugin url fields

---

.gitignore
.vscode/extensions.json
.vscode/settings.template.json
rush.json
scripts/hooks/post-rush-install.sh
scripts/hooks/setup-vscode-settings.sh

chore: auto generate vscode settings for first time install

---

frontend/packages/data/knowledge/knowledge-resource-processor-base/src/constants/common.ts

feat(frontend): remove .doc from accepted file types

---

backend/domain/memory/variables/entity/variable_meta_schema.go

style: Changes that do not affect the meaning of the code (white space, formatting, missing semi-colons, etc)
样式: 修复方法名注释中的拼写错误
en: This PR corrects a minor typo in a code comment, changing GetObjetProperties to GetObjectProperties. This improves code readability and consistency, especially for developers navigating the codebase or using search tools.
zh: 本次 PR 修复了代码注释中的拼写错误，将 GetObjetProperties 更正为 GetObjectProperties。该修改有助于提升代码可读性和一致性，尤其是在开发者查阅代码或使用搜索工具时。
None.

style(variable_meta_schema): correct typo in comment

---

backend/domain/memory/variables/entity/variable_meta_schema.go

style: Changes that do not affect the meaning of the code (white space, formatting, missing semi-colons, etc)
style: 删除一行不必要的注释
en:This PR removes a redundant comment line to improve code cleanliness. No functional or logic changes involved.
zh(optional): 该 PR 删除了一行多余的注释，用于提升代码整洁度，不涉及任何功能或逻辑上的改动。
N/A

style: remove an unnecessary comment line

---

backend/api/model/crossdomain/knowledge/knowledge.go

Initialize contentMap with make() to avoid potential nil map panic when accessing the map later in the code.
en:
zh(optional):

fix(knowledge): initialize contentMap to prevent nil map panic

---

.github/workflows/claude.yml

chore: setup claude for ci

---

backend/domain/plugin/service/plugin_draft.go

openapi3Operation parameters not equal

fix(plugin):  openapi3Operation parameters not equal

---

frontend/packages/community/component/src/card/components/container/index.module.less

fix: remove plugin card cursor

---

backend/conf/model/template/model_template_ark_doubao-1.5-thinking-pro.yaml
backend/conf/model/template/model_template_ark_doubao-1.5-thinking-vision-pro.yaml
backend/conf/model/template/model_template_ark_doubao-1.5-vision-pro.yaml
backend/conf/model/template/model_template_ark_doubao-seed-1.6-flash.yaml
backend/conf/model/template/model_template_ark_doubao-seed-1.6-thinking.yaml
backend/conf/model/template/model_template_ark_doubao-seed-1.6.yaml
backend/conf/model/template/model_template_ark_volc_deepseek-r1.yaml
backend/conf/model/template/model_template_ark_volc_deepseek-v3.yaml
backend/conf/model/template/model_template_claude.yaml
backend/domain/agent/singleagent/internal/agentflow/suggest_prompt.go
backend/domain/agent/singleagent/internal/agentflow/system_prompt.go
backend/infra/contract/chatmodel/config.go
backend/infra/impl/chatmodel/default_factory.go

fix(model): support the configuration to disable reasoning

---

backend/domain/agent/singleagent/internal/agentflow/callback_reply_chunk.go

fix(model): Remove the validation that tool_call_id must be empty.

---

.claude/agents/frontend-infrastructure-expert.md
.vscode/settings.template.json
frontend/config/ts-config/tsconfig.base.json

chore: impprove ts server perf of vscode

---

backend/domain/workflow/internal/execute/callback.go

fix: workflow tool returns real stream with typewriter effect.

fix: workflow onEndWithStream handles stream asynchronously

---

backend/domain/memory/database/service/database_impl.go

优化数据库线上数据展示界面
en:
Fixed the issue where bstudio_comnector_uid query was inaccurate when listing records in the database.
Database developers can see the data written by users
zh(optional): 
修复数据库列举records时bstudio_connector_uid查询不准的问题。
数据库开发者可以看到用户写入的数据

fix: Optimize the online data tab display of data tables

---

backend/application/workflow/workflow.go
backend/crossdomain/workflow/plugin/plugin.go
backend/crossdomain/workflow/plugin/plugin_test.go
backend/domain/workflow/crossdomain/plugin/plugin.go
backend/domain/workflow/entity/message.go
backend/domain/workflow/internal/canvas/adaptor/to_schema.go
backend/domain/workflow/internal/execute/callback.go
backend/domain/workflow/internal/execute/event_handle.go

en:
zh(optional): 
https://github.com/coze-dev/coze-studio/issues/414

fix: delete redundant fields in plugin output data

---

backend/infra/impl/document/searchstore/vikingdb/vikingdb_searchstore.go

fix: A bug fix
修复: 在处理 part 时补充缺失的进度条更新逻辑
en: This PR adds a missing piece of logic that updates the progress bar during part processing. Without this code, the progress bar remains unchanged, which may mislead users or cause incomplete feedback during execution.
zh(optional): 本次 PR 补充了在处理 part 时更新进度条的逻辑。此前由于缺失该逻辑，进度条不会正确更新，可能导致用户无法获得完整的处理反馈。
None.

fix(knowledge): add missing progress bar update

---

backend/domain/workflow/internal/nodes/llm/llm.go

fix(workflow): model reasoning

---

backend/api/handler/coze/workflow_service_test.go
backend/application/workflow/init.go
backend/domain/workflow/internal/compose/designate_option.go
backend/domain/workflow/service/global_handler.go

…n on node setup
en:correct token count error caused by ctxcache initialization on node setup
zh(optional): 修复节点初始化时使用ctxcache init导致的token计数错误

fix: correct token calculation error caused by ctxcache init

---

backend/domain/knowledge/service/knowledge.go

fix: Optimize the knowledge domain idgen code
优化知识库domain idgen代码
、
en:Add retry for idgen
zh(optional): 为idgen增加重试
Fixes #472

fix(knowledge): Optimize the knowledge domain idgen code

---

docker/docker-compose.yml
docker/nginx/conf.d/default.conf
docker/nginx/nginx.conf
frontend/.dockerignore
frontend/Dockerfile

feat(ci): Frontend supports Docker build.

---

backend/application/workflow/workflow.go
backend/domain/workflow/entity/node_meta.go
backend/domain/workflow/internal/compose/node_runner.go
backend/domain/workflow/internal/compose/workflow_run.go
backend/domain/workflow/internal/execute/consts.go
backend/domain/workflow/internal/execute/context.go

feat: remove default timeout for both nodes and workflow

---

backend/domain/agent/singleagent/internal/agentflow/callback_reply_chunk.go
backend/domain/conversation/agentrun/service/agent_run_impl.go
backend/types/consts/consts.go
backend/types/errno/conversation.go
docker/.env.debug.example

chore:  print the original error log in debug mode

---

backend/conf/plugin/pluginproduct/plugin_meta.yaml
docker/.env.debug.example
docker/.env.example

fix(plugin): aes secret env contains illegal characters

---

frontend/apps/coze-studio/src/routes.tsx

feat(routing): add redirect route for auth success page

---

backend/domain/agent/singleagent/internal/agentflow/agent_flow_builder.go
backend/domain/agent/singleagent/internal/agentflow/node_chat_model.go

fix(singleagent): agent model configuration

---

helm/charts/opencoze/templates/mysql-init-job.yaml
helm/charts/opencoze/templates/rocketmq-broker-statefulset.yaml

en: update the FQDN for service name, otherswize the task in the initContainer will report invalid service name
zh(optional):

fix(ci): update FQDN for service name in initContainer

---

Makefile
docker/docker-compose-debug.yml

1. 同步配置到docker-compose-debug.yml

fix: sync docker-compose.yml es init to docker-compose-debug.yml

---

backend/crossdomain/workflow/database/database.go
backend/domain/workflow/crossdomain/database/database.go
backend/domain/workflow/internal/nodes/database/common.go

en:Correct userID propagation for agent-triggered workflows
zh(optional): 修复agent场景下调用workflow时userID传递有误的问题

fix: Correct userID propagation for agent-triggered workflows

---

backend/crossdomain/workflow/plugin/plugin.go

en:correct userID propagation for plugin nodes in agent-run scene
zh(optional): 修复agent场景调用工作流时，插件节点获取userID有误的问题

fix: correct userID propagation for plugin nodes in agent-run scene

---

backend/infra/impl/embedding/http/http.go

… types
feat
en:
- http embedding using /support_status to return support vector types 
zh(optional): 
- http embedding 新增 /support_status 返回模型支持的向量类型

feat: http embedding using /support_status to return support vector types

---

backend/infra/impl/document/searchstore/vikingdb/vikingdb_manager.go

fix
en:
- fix sparse vector field init error when using vikingdb embedding bge-m3
zh(optional): 
- fix 使用 vikingdb bge-m3 向量化时稀疏向量列初始化问题

fix: sparse vector field init error when using viking embedding

---

backend/application/workflow/workflow.go
backend/crossdomain/workflow/plugin/plugin.go
backend/crossdomain/workflow/plugin/plugin_test.go
backend/domain/workflow/crossdomain/plugin/plugin.go
backend/domain/workflow/crossdomain/plugin/pluginmock/plugin_mock.go

en:Correctly handle 'Array Item' when converting APIParameter
zh(optional): 修复将APIParameter转换时未处理Array Item字段的问题

fix: Correctly handle 'Array Item' when converting APIParameter

---

backend/application/search/resource_search.go

fix(app): avoid nil panic

---

backend/domain/workflow/entity/node_meta.go

fix display name for Custom SQL Node

fix: display name for custom SQL node

---

docker/.env.debug.example
docker/.env.example
docker/docker-compose.yml

1. Update the Docker image names for both the server and the web.
2. Set the default port access to localhost only.

chore(ci): 1. Update the Docker image names for both the server and the web.2. Set the default port access to localhost only.

---

README.md
README.zh_CN.md

docs: readme security risk tips

---

backend/application/singleagent/single_agent.go

fix(singleagent): remove code

---

backend/api/model/conversation/message/message.go
idl/conversation/message.thrift

fix(singleagent): openapi message list field type

---

backend/api/handler/coze/workflow_service_test.go
backend/application/workflow/workflow.go
backend/domain/workflow/internal/nodes/entry/entry.go
backend/domain/workflow/internal/nodes/variableaggregator/variable_aggregator.go

fix(ci): correct workflow unit test

---

backend/application/workflow/workflow.go

fix: correctly transform single-field Array<object> variables

---

backend/infra/impl/storage/s3/s3.go

optimize(infra): remove tautological condition
optimize(infra): 移除一个条件始终为true的if分支
en:
zh(optional):

optimize(infra): remove tautological condition

---

frontend/packages/studio/open-platform/open-chat/src/components/studio-open-chat/provider/coz-sdk/api-adapter/use-clear-history.ts

fix: chatflow create api

---

frontend/packages/common/chat-area/plugin-chat-shortcuts/src/utils/get-ui-mode-by-biz-scene.ts

fix: 修复 ts 错误

---

frontend/config/ts-config/tsconfig.base.json

fix: tsconfig base

---

frontend/packages/common/chat-area/chat-area/src/context/chat-area-context/chat-area-callback.ts
frontend/packages/studio/open-platform/open-chat/src/chat/builder-chat/coze-chat.tsx

fix: ts-check

---

backend/domain/conversation/agentrun/internal/chatflow_run.go

fix(singleagent): chatflow input concat

---

docker/docker-compose.yml

fix(ci): mysql ddl apply

---

docker/docker-compose-debug.yml
docker/docker-compose.yml

fix(ci): ddl apply

---

.gitignore
Makefile
backend/application/base/appinfra/app_infra.go
backend/infra/impl/document/searchstore/oceanbase/consts.go
backend/infra/impl/document/searchstore/oceanbase/convert.go
backend/infra/impl/document/searchstore/oceanbase/factory.go
backend/infra/impl/document/searchstore/oceanbase/oceanbase_manager.go
backend/infra/impl/document/searchstore/oceanbase/oceanbase_searchstore.go
backend/infra/impl/document/searchstore/oceanbase/register.go
backend/infra/impl/oceanbase/oceanbase.go
backend/infra/impl/oceanbase/oceanbase_official.go
backend/infra/impl/oceanbase/types.go
docker/.env.debug.example
docker/.env.example
docker/docker-compose-oceanbase.yml
docker/docker-compose-oceanbase_debug.yml
docs/oceanbase-integration-guide-en.md
docs/oceanbase-integration-guide.md
scripts/setup/oceanbase_env.sh
scripts/setup/server.sh

feat: A new feature with  oceanbase vector support
添加oceanbase的向量存储和检索的支持
en:
- Added data source management for Oceanbase
- Added support for oceanbase vector storage and retrieval
- Add the MakeFile command to start the oceanbase image environment with one click
- Added vector support documentation for oceanbase:
- docs/oceanbase-integration-guide-en.md
- docs/oceanbase-integration-guide.md
zh(optional): 
- 添加了oceanbase的数据源管理
- 添加了oceanbase向量存储和检索支持
- 增加MakeFile命令，可通过make oceanbase一键启动oceanbase的镜像环境
- 添加了oceanbase的向量支持文档：
- docs/oceanbase-integration-guide-en.md
- docs/oceanbase-integration-guide.md
Close #1811

feat: add oceanbase vector support

---

backend/domain/workflow/internal/nodes/conversation/clearconversationhistory.go

fix(workflow): Resolve variable shadowing issue in ClearConversationHistory

---

backend/api/handler/coze/workflow_service_test.go

feat(workflow): add unit tests for conversation_manager && chatflow_role interface

---

backend/infra/impl/es/es7.go
backend/infra/impl/es/es8.go
backend/infra/impl/es/es_impl.go
backend/pkg/parsex/address.go
docker/.env.debug.example
docker/.env.example

es多节点配置的时候，这里需要一个数组，但是现在只是一个字符串

  feat(infra): es支持多节点配置

---

backend/application/workflow/workflow.go

fixes: https://github.com/coze-dev/coze-studio/pull/2004

fix: event must be capitalized when streaming

---

backend/infra/impl/oceanbase/oceanbase.go
backend/infra/impl/oceanbase/oceanbase_official.go
docker/docker-compose-oceanbase.yml
docker/docker-compose-oceanbase_debug.yml
docs/oceanbase-integration-guide-en.md
docs/oceanbase-integration-guide.md
helm/charts/opencoze/templates/oceanbase-secret.yaml
helm/charts/opencoze/templates/oceanbase-service.yaml
helm/charts/opencoze/templates/oceanbase-serviceaccount.yaml
helm/charts/opencoze/templates/oceanbase-statefulset.yaml
helm/charts/opencoze/values.yaml

feat,fix,docs
oceanbase的向量检索sql防注入和补充helm部署模版
en:
Helm deployment should be supplemented, and Oceanbase's vector retrieval SQL should be encapsulated using GORM's API
zh(optional): 
补充 Helm 部署模版，并使用 GORM 的 API 封装 Oceanbase 的向量检索 SQL
Close #2047

feat(infra): Oceanbase Vector Sql Prevent SQL injection And Complementary helm deployment

---

backend/conf/model/template/model_template_openai.yaml
backend/go.mod
backend/go.sum
backend/infra/contract/chatmodel/config.go
backend/infra/impl/chatmodel/default_factory.go

fix(model): the OpenAPI model supports max_completion_tokens.

---

backend/application/conversation/openapi_agent_run.go

fix(singleagent): v3/chat panic when ext is nil

---

docker/.env.debug.example
docker/.env.example

style: correct formatting env variables

style: correct formatting env ES_NUMBER variables

---

backend/types/consts/consts.go
docker/.env.debug.example
docker/.env.example
docker/docker-compose-debug.yml
docker/docker-compose-oceanbase.yml
docker/docker-compose-oceanbase_debug.yml
docker/docker-compose.yml

See details at https://github.com/bitnami/containers/issues/83267

fix(infra): resolve issue with unavailable Bitnami image
